enum Types {
  // Locale
  SET_USER_PREFERRED_LOCALE = 'SET_USER_PREFERRED_LOCALE',

  // Notifications
  SET_NOTIFICATIONS = 'SET_NOTIFICATIONS',
  SET_NOTIFICATIONS_ERROR = 'SET_NOTIFICATIONS_ERROR',
  ADD_NOTIFICATION = 'ADD_NOTIFICATION',
  ADD_NOTIFICATIONS = 'ADD_NOTIFICATIONS',
  DELETE_NOTIFICATION = 'DELETE_NOTIFICATION',
  MARK_NOTIFICATION_AS_READ = 'MARK_NOTIFICATION_AS_READ',
  RESET_NOTIFICATIONS = 'RESET_NOTIFICATIONS',

  // Environments
  SWITCH_ENVIRONMENT = 'SWITCH_ENVIRONMENT',
  //Authentication
  SET_ONBOARDED = 'SET_ONBOARDED',

  //user
  SET_USER = 'SET_USER',
  LOGOUT_USER = 'LOGOUT_USER',

  //App
  SET_MIN_VERSION = 'SET_MIN_VERSION',
  APP_LOCKED = 'APP_LOCKED',
  APP_UNLOCKED = 'APP_UNLOCKED',
  GET_MIN_VERSION = 'GET_MIN_VERSION',
  REQUIRE_PIN_TO_OPEN = 'REQUIRE_PIN_TO_OPEN',
  SET_APP_STATE = 'SET_APP_STATE',
  SET_LOCK_PIN = 'SET_LOCK_PIN',
  GET_LOCK_PIN = 'GET_LOCK_PIN',
  SET_LOCK_PIN_AVAILABLE = 'SET_LOCK_PIN_AVAILABLE',
  SET_LOCKING_ENABLED = 'SET_LOCKING_ENABLED',
  SET_FINGERPRINT_ENABLED = 'SET_FINGERPRINT_ENABLED',
  SET_BIOMETRIC_ENABLED = 'SET_BIOMETRIC_ENABLED',
  SKIP_BIOMETRICS = 'SKIP_BIOMETRICS',
  FACE_ID_ENABLED = 'FACE_ID_ENABLED',
  SKIP_PIN_SET_UP = 'SKIP_PIN_SET_UP',

  //TA
  CLOCK_IN_OUT = 'CLOCK_IN_OUT',
  ADD_CLOCKINOUT = 'ADD_CLOCKINOUT',
  ADD_TA_ATTEMPTS = 'ADD_TA_ATTEMPTS',
  EDIT_TA_ATTEMPT = 'EDIT_TA_ATTEMPT',
  DELETE_CLOCKINOUT = 'DELETE_CLOCKINOUT',
  RESET_CLOCKINOUT = 'RESET_CLOCKINOUT',

  SET_NETWORK = 'SET_NETWORK',

  SHOW_AMOUNT = 'SHOW_AMOUNT',
  //EXPENSES
  SET_EXPENSE_ITEM = 'SET_EXPENSE_ITEM',
}

export default Types
