export interface TEmployee {
  id: number
  employee_no: string
  profile_picture: string
  department_id: number
  supervisor_id: any
  company_id: number
  person_id: number
  pin_no: string
  id_no: string
  nssf_no: any
  nhif_no: any
  pension_no: any
  employment_type: string
  date_employed: string
  entitled_leave_days: number
  designation_id: number
  date_confirmed: any
  bank_details_id: number
  employeeclass_id: any
  status: string
  created_at: string
  updated_at: string
  payment_frequency: string
  daily_rate: string
  hourly_rate: string
  daily_hours: any
  income_tax: string
  deduct_nhif: string
  deduct_nssf: string
  tax_exemption_amount: any
  tax_certificate_no: any
  payment_method: string
  off_days: string
  contract_end_date: any
  previous_nos: string
  education: string
  marital_status: string
  ethnic_group: any
  next_of_kin: any[]
  insurance_relief: string
  exit_date: any
  voluntary_provident: string
  zkteco_account_no: any
  smile_id: any
  insurance_value_type: string
  insurance_premium_amount: string
  transfer_reason: any
  other_insurance_premium: string
  rating: string
  graduation_date: string
  on_probation: number
  probation_start_date: any
  probation_end_date: any
  remark: any
  currency_id: number
  pension_rate: string
  deduct_pension: any
  esop_id: any
  employment_type_id: number
  salary: string
  customize_pension_rate: number
  customized_pension_ee_rate: string
  customized_pension_er_rate: string
  customized_pension_upper_limit: string
  customized_pension_amount_type: string
  is_non_resident: number
  with_nita: number
  sub_team_id: number
  withholding_tax_rate: string
  deduct_nhis: number
  nhf_no: any
  pension_provider_id: any
  can_resend_credentials: number
  is_secondary_employee: number
  is_device_overtime_eligible: number
  country_id: number
  tax_residential_status: string
  rest_days: any
  is_user: boolean
  project_id: number
  employee_name: string
  project_title: string
  shift_name: string
  shift_ids: any[]
  is_blacklisted: boolean
  on_training: boolean
  salary_start_date: string
  salary_reference: string
  payment_policy: string
  supervisor_name: string
  supervisor_person_id: string
  department_name: string
  branch_name: string
  designation_name: string
  currency_name: string
  currency_code: string
  employment_type_name: string
  deduct_tax: string
  tax_type: string
  attendance_policy: any
  employee_no_prefix: string
  age: number
  supervisor_phone: string
  supervisor_email: string
  supervisor_profile_picture: string
  supervisor_country: string
  supervisor_role_name: string
  on_duty: boolean
  shift: any
  pension_provider_name: string
  payment_currency_id: number
  payment_currency_code: string
  payment_currency_name: string
  verification_process_done: number
  has_verified_bank_account: number
  salary_daily_rate: string
  join_date: string
  length_of_service: string
  eligible_for_leave: number
  exit_reason: string
  country: Country
  person: Person
  address: Address
  bank_details: BankDetails
  employee_movements: any[]
  referees: any[]
  employee_company: EmployeeCompany
  pension_provider: any
}

export interface Country {
  id: number
  flag: string
  name: string
  alpha_two_code: string
  alpha_three_code: string
  numeric_code: string
  phone_code: string
  currencycode: string
  currencyname: string
  currencysymbol: any
  capital: string
  citizenship: string
  created_at: any
  updated_at: string
  status: string
  enabled: number
  wallet_currency_id: number
  billing_currency_id: number
  remitly_supported: number
  currency_id: number
  timezone: string
}

export interface Person {
  id: number
  first_name: string
  othernames: string
  surname: string
  dob: string
  company_id: number
  title: string
  gender: string
  created_at: string
  updated_at: string
  marital_status: string
}

export interface Address {
  id: number
  phone_no: string
  mobile_no: string
  email: string
  postal_address: string
  zip_code: any
  county: any
  city: any
  road: any
  website: any
  facebook: any
  twitter: any
  linkedin: any
  document_link: any
  country_id: number
  person_id: number
  nationality_id: number
  created_at: string
  updated_at: string
  personal_email: string
  citizenship: string
  country_of_residence: string
}

export interface BankDetails {
  id: number
  payment_method: string
  bank_id: any
  branch_id: any
  account_name: string
  account_no: string
  status: string
  created_at: string
  updated_at: string
  country_id: number
  currency_id: number
  routing_number: any
  swift_code: string
  custom_bank_name: string
  bank_address: string
  recipient_first_name: string
  recipient_last_name: string
  recipient_email_address: string
  recipient_address: string
  recipient_mobile_number: string
  postal_code: any
  street_number: any
  street_name: any
  city: any
  date_of_birth: any
  subdivision_id: any
  account_number_type: any
  verified_account_name: any
  is_valid_account: number
  verification_process_done: number
  verification_response: any
  branch_name: string
  bank_name: string
  currency_name: string
  country_name: string
  currency_code: string
  bank: Bank
  branch: Branch
}

export interface Bank {
  name: string
}

export interface Branch {
  name: string
}

export interface EmployeeCompany {
  id: number
  slogan: any
  address_id: number
  name: string
  username: string
  bank_details_id: number
  pin_no: string
  logo: string
  currency_id: number
  country_id: number
  vat_no: any
  user_id: number
  balance: string
  date_started: string
  is_personal: number
  has_trial: string
  created_at: string
  updated_at: string
  nssf_no: string
  nhif_code: string
  sector: string
  two_way_auth: any
  two_way_verified: number
  type: string
  theme: string
  is_head_office: number
  head_office_id: number
  employee_no_prefix: any
  status: string
  sector_id: number
  company_code: string
  balance_lower_limit: string
  number_of_employees: number
  foreign_currency_enabled: number
  product_admin_pay_advance_company: number
  helb_code: any
  deleted_at: any
  accepted_terms_and_conditions: number
  wallet_id: number
  wallet_name: string
  owner_mobile: string
  owner_email: string
  owner_name: string
  currency_code: string
  currency_name: string
  head_office: HeadOffice
}

export interface HeadOffice {
  id: number
  slogan: string
  address_id: number
  name: string
  username: string
  bank_details_id: number
  pin_no: string
  logo: string
  currency_id: number
  country_id: number
  vat_no: string
  user_id: number
  balance: string
  date_started: string
  is_personal: number
  has_trial: string
  created_at: string
  updated_at: string
  nssf_no: any
  nhif_code: any
  sector: string
  two_way_auth: any
  two_way_verified: number
  type: string
  theme: string
  is_head_office: number
  head_office_id: number
  employee_no_prefix: any
  status: string
  sector_id: number
  company_code: any
  balance_lower_limit: string
  number_of_employees: number
  foreign_currency_enabled: number
  product_admin_pay_advance_company: number
  helb_code: any
  deleted_at: any
  accepted_terms_and_conditions: number
  wallet_id: number
  wallet_name: string
  owner_mobile: string
  owner_email: string
  owner_name: string
  currency_code: string
  currency_name: string
}
